<?php

declare(strict_types=1);

namespace Spora\Http;

use Spora\Auth\AuthService;
use Spora\Models\Agent;
use Spora\Models\MediaAsset;
use Spora\Services\AssetStorageException;
use Spora\Services\DatabaseAssetStore;
use Spora\Services\LocalAssetStore;
use Spora\Services\MediaArchive\MediaArchiveService;
use Spora\Services\PrincipalResolver;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Serves files referenced by the {@see MediaArchiveService}.
 *
 * Route: `GET /api/v1/assets/{filename}` — registered with
 * {@see Middleware\AuthMiddleware} (see
 * {@see \Spora\Core\RouteDefinitions}). URL form is
 * `/api/v1/assets/<uuid>`, where the UUID is the row's primary key.
 *
 * Authorization is ownership-based, not URL-based: the URL is now the
 * row's primary key, so anyone who sees the URL could otherwise fetch
 * the bytes. The controller mirrors the listing query's ownership
 * union — direct upload (`media_assets.user_id`) or generated by an
 * agent the caller owns (`media_assets.agent_id -> agents.user_id`).
 * Admins bypass. Non-owners get a 404 to avoid leaking UUID existence.
 *
 * Migration 0067 cut `agents.user_id` and routed ownership through
 * `PrincipalResolver::ownerUserId()`. {@see \Spora\Models\Agent}'s
 * legacy `getUserIdAttribute()` is a shim only — this controller goes
 * straight to the resolver so the principals-and-groups model is
 * explicit (the legacy accessor would still work for user-principals,
 * but resolve wrongly for group-principals because the first
 * `owner`-of-the-group fallback is not the "ownership" the asset
 * controller wants).
 *
 * Pre-refactor rows whose URL was returned to the LLM in the legacy
 * `<token>.<ext>` HMAC form skip the ownership check — they were minted
 * under the "URL is the token" model and predate this control.
 */
final class AssetController
{
    /** 24h browser cache: asset bytes don't change post-ingest. */
    private const CACHE_HEADER = 'private, max-age=86400';

    public function __construct(
        private readonly MediaArchiveService $archive,
        private readonly DatabaseAssetStore $database,
        private readonly LocalAssetStore $local,
        private readonly AuthService $auth,
        private readonly ?PrincipalResolver $resolver = null,
    ) {}

    public function show(string $filename): Response
    {
        // Accept both `/api/v1/assets/<uuid>` and `/api/v1/assets/<uuid>.<ext>`.
        // UUIDs never contain dots, so a trailing `.<ext>` is safe to strip
        // here without affecting the legacy HMAC-token fallback path.
        $uuid = $this->stripExtension($filename);

        $asset = $this->archive->find($uuid);
        if ($asset !== null) {
            return $this->streamOwnedAsset($asset);
        }

        $resolved = $this->local->resolve($filename);
        if ($resolved !== null) {
            $response = new BinaryFileResponse($resolved['path'], 200, ['Content-Type' => $resolved['mime']]);
            $response->headers->set('Cache-Control', self::CACHE_HEADER);
            return $response;
        }

        return $this->notFound();
    }

    /**
     * Return the UUID portion of a public asset filename, stripping any
     * `.ext` suffix the browser appended for filename hints. UUIDs match
     * `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` (36 chars); anything after
     * the 36th char is treated as the extension. Inputs without a `.`
     * are returned unchanged.
     */
    private function stripExtension(string $filename): string
    {
        if (preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(.+)$/i', $filename) === 1) {
            return substr($filename, 0, 36);
        }
        return $filename;
    }

    /**
     * Non-owners get the standard 404 envelope so we don't leak which
     * UUIDs exist in the archive.
     */
    private function streamOwnedAsset(MediaAsset $asset): Response
    {
        if (!$this->canAccessAsset($asset)) {
            return $this->notFound();
        }
        return $this->streamAsset($asset);
    }

    /**
     * Admins bypass; everyone else must own the asset either directly
     * (`user_id == me`) or via the agent that produced it
     * (`agent.principal_id -> principals.ownerUserId() == me`). Mirrors
     * {@see MediaArchiveService::list()}'s ownership union so the asset
     * bytes are reachable for every row the listing endpoint surfaces
     * — including direct uploads that have no `task_id` and no
     * `agent_id` of their own.
     */
    private function canAccessAsset(MediaAsset $asset): bool
    {
        $userId = $this->auth->currentUserId();
        if ($userId === null) {
            return false;
        }
        return $this->auth->isAdmin() || $this->ownsAsset($asset, $userId);
    }

    /**
     * Single arm of the ownership union: does the given user own this row
     * directly (uploaded it themselves) or own the agent that produced it?
     * Split out so {@see canAccessAsset()} stays under the SonarQube
     * 3-return brain-overload ceiling.
     */
    private function ownsAsset(MediaAsset $asset, int $userId): bool
    {
        if ($asset->user_id !== null && (int) $asset->user_id === $userId) {
            return true;
        }
        if ($asset->agent_id === null) {
            return false;
        }
        $agent = (new Agent())->find($asset->agent_id);
        if ($agent === null) {
            return false;
        }
        $resolver = $this->resolver ?? new PrincipalResolver();
        $ownerUserId = $resolver->ownerUserId((int) $agent->principal_id);
        return $ownerUserId !== null && $ownerUserId === $userId;
    }

    private function streamAsset(MediaAsset $asset): Response
    {
        try {
            $payload = match ($asset->storage_mode) {
                'data_url' => $this->database->read($asset),
                'local'    => $this->local->readFromAsset($asset),
                'external' => throw new AssetStorageException("External assets have no Spora-side payload"),
                default    => throw new AssetStorageException("Unsupported storage_mode: {$asset->storage_mode}"),
            };
        } catch (AssetStorageException) {
            return $this->notFound();
        }

        if (array_key_exists('bytes', $payload)) {
            // StreamedResponse avoids loading the BLOB into PHP memory
            // twice (once via read(), once via echo).
            $bytes = (string) $payload['bytes'];
            $mime  = (string) $payload['mime'];
            $response = new StreamedResponse(static function () use ($bytes): void {
                echo $bytes;
            }, 200, [
                'Content-Type'   => $mime,
                'Content-Length' => (string) strlen($bytes),
                'Cache-Control'  => self::CACHE_HEADER,
            ]);
            $this->applyContentDisposition($response, $asset);
            return $response;
        }

        $path = (string) $payload['path'];
        $mime = (string) $payload['mime'];
        $response = new BinaryFileResponse($path, 200, ['Content-Type' => $mime]);
        $response->headers->set('Cache-Control', self::CACHE_HEADER);
        $this->applyContentDisposition($response, $asset);
        return $response;
    }

    /**
     * Set `Content-Disposition: attachment; filename="..."` when the row
     * carries a user-facing `filename`. Falls back to the opaque UUID +
     * extension so the browser still gets a sensible default download
     * name for legacy rows.
     */
    private function applyContentDisposition(Response $response, MediaAsset $asset): void
    {
        $name = $asset->filename !== null && $asset->filename !== ''
            ? $asset->filename
            : $asset->publicUrl();
        $response->headers->set(
            'Content-Disposition',
            sprintf('attachment; filename="%s"', addcslashes(basename($name), '"\\')),
        );
    }

    private function notFound(): JsonResponse
    {
        return new JsonResponse(
            ['error' => ['code' => 'asset_not_found', 'message' => 'Asset not found.']],
            404,
        );
    }
}
